### PR TITLE
Improve Documentation in Combinator Blueprint Strings

### PR DESCRIPTION
**Pull request by JakobDegen**
Changes the combinator blueprint strings to indicate that documentation should be added where possible. Also changes the blueprint strings for two circuits to include this documentation and the improved designs which had not been included.

### CODE REVIEW

**Review by Halke1986 — APPROVED** [review]
Nice use of .md files for bps.

**Comment by tzwaan** [comment]
On the one hand I like the .md files because of the descriptions.
On the other hand, this makes it impossible to provide the raw link of the blueprint to something like the blueprintbot on discord or the subreddit.

**Comment by JakobDegen** [comment]
@tzwaan ah, this is a good point and I had not considered this. I don't see a great resolution to this at the moment though, so leaving this open for now is probably alright.

**Comment by tzwaan** [comment]
One solution would be to have 2 files for each blueprint. A .blueprint file for the string and an .md file for the description, and just give them the same name.

**Comment by tzwaan** [comment]
I think a good solution would be to just make each blueprint a folder, in which there is a blueprint.string and README.md file.
The name of the blueprint would just be the name of the folder. That way the description and blueprint are still contained together, the readme is actually readable when you enter the folder, since that's what github does by default with readme files, and you can still link directly to the raw blueprint file.

**Pull request merged**
